
# Site settings
title: Charlotte
email: "kimt583@newschool.edu"
description: > # this means to ignore newlines until "baseurl:"
  Labradora amável, brincalhona e esfomiada, mas que acima de tudo, feliz! <a href="#">@charlotte</a>
baseurl: "/labrador-jekyll-theme" # the subpath of your site, e.g. /blog
url:  "kimt583.github.io"
logo: "/assets/img/logo.png"

# Build settings
paginate: 10
paginate_path: "/blog/page:num/"
markdown: kramdown
sass:
    sass_dir: assets/css/sass
    style: compressed

gems:
  - jekyll-gist
  - jekyll-paginate
